#ifndef lint
static const char yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93";
#endif

#include <stdlib.h>
#include <string.h>

#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define YYPATCH 20070509

#define YYEMPTY (-1)
#define yyclearin    (yychar = YYEMPTY)
#define yyerrok      (yyerrflag = 0)
#define YYRECOVERING (yyerrflag != 0)

extern int yyparse(void);

static int yygrowstack(void);
#define YYPREFIX "yy"
#line 47 "parser.y"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "decl.h"
#include "stmt.h"
#include "expr.h"
#include "type.h"
#include "param_list.h"
#include "symbol.h"
/*
Clunky: Manually declare the interface to the scanner generated by flex. 
*/
extern char *yytext;
extern int yylex();
extern int yyerror(char *str);
extern void convertString(char *string);

/*
Clunky: Keep the final result of the parse in a global variable,
so that it can be retrieved by main().
*/
struct decl *parser_result = 0;
#line 71 "parser.y"
typedef union {
	struct decl *decl;
	struct expr *expr;
	struct stmt *stmt;
	struct type *type;
	struct param_list *param_list;
	char *name;
	int integer;
} YYSTYPE;
#line 56 "parser.tab.c"
#define TOKEN_PRINT 257
#define TOKEN_FUNCTION 258
#define TOKEN_FOR 259
#define TOKEN_IF 260
#define TOKEN_ELSE 261
#define TOKEN_RETURN 262
#define TOKEN_LEFT_BRACE 263
#define TOKEN_RIGHT_BRACE 264
#define TOKEN_LEFT_PAREN 265
#define TOKEN_RIGHT_PAREN 266
#define TOKEN_LEFT_BRACKET 267
#define TOKEN_RIGHT_BRACKET 268
#define TOKEN_STRING 269
#define TOKEN_INTEGER 270
#define TOKEN_CHAR 271
#define TOKEN_VOID 272
#define TOKEN_BOOLEAN 273
#define TOKEN_ARRAY 274
#define TOKEN_GE 275
#define TOKEN_LE 276
#define TOKEN_EQ 277
#define TOKEN_NE 278
#define TOKEN_LT 279
#define TOKEN_GT 280
#define TOKEN_AND 281
#define TOKEN_OR 282
#define TOKEN_NOT 283
#define TOKEN_INCREMENT 284
#define TOKEN_DECREMENT 285
#define TOKEN_ADD 286
#define TOKEN_SUBTRACT 287
#define TOKEN_MULTIPLY 288
#define TOKEN_DIVIDE 289
#define TOKEN_MODULUS 290
#define TOKEN_EXPONENTIATE 291
#define TOKEN_ASSIGN 292
#define TOKEN_COMMA 293
#define TOKEN_COLON 294
#define TOKEN_SEMICOLON 295
#define TOKEN_TRUE 296
#define TOKEN_FALSE 297
#define TOKEN_CHAR_LITERAL 298
#define TOKEN_INTEGER_LITERAL 299
#define TOKEN_STRING_LITERAL 300
#define TOKEN_IDENTIFIER 301
#define YYERRCODE 256
short yylhs[] = {                                        -1,
    0,    1,    1,    2,    2,    2,   15,   15,   17,   17,
   17,   17,   17,   17,   17,   16,   16,   16,   18,   18,
   19,   19,    3,    3,    4,    4,    4,    5,    5,    5,
    5,    5,    5,    5,    6,    6,    6,    7,    7,    7,
    7,    8,    8,    9,    9,    9,   10,   10,   10,   11,
   11,   12,   12,   13,   13,   14,   14,   14,   14,   14,
   14,   14,   14,   14,   14,   20,   20,   20,   20,   20,
   20,   20,   21,   21,   22,   22,   23,   34,   68,   35,
   38,   39,   33,   31,   32,   36,   37,   60,   61,   64,
   62,   65,   63,   66,   67,   44,   46,   47,   42,   45,
   43,   40,   41,   54,   55,   56,   48,   49,   50,   51,
   52,   53,   29,   57,   28,   30,   58,   59,   27,   26,
   25,   24,
};
short yylen[] = {                                         2,
    1,    2,    1,    6,    4,    7,    1,    1,    1,    2,
    3,    3,    9,    7,    3,    5,    7,    9,    1,    0,
    2,    1,    3,    1,    3,    3,    1,    3,    3,    3,
    3,    3,    3,    1,    3,    3,    1,    3,    3,    3,
    1,    3,    1,    2,    2,    1,    2,    2,    1,    1,
    0,    1,    0,    3,    1,    1,    4,    1,    1,    1,
    1,    1,    3,    3,    4,    1,    1,    1,    1,    1,
    5,    5,    1,    0,    1,    3,    3,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,
};
short yydefred[] = {                                      0,
  122,    0,    1,    0,    0,    2,  115,    0,   79,   90,
   91,   92,   93,   94,   95,    0,   66,   67,   68,   69,
   70,    0,    0,  113,  116,    0,    5,   88,    0,    0,
   84,   86,  104,  108,  117,  118,  119,  120,  121,    0,
    0,   27,    0,    0,   41,    0,   46,    0,    0,   59,
   58,   60,    0,    0,    0,    0,   61,   62,    0,    0,
    0,    0,    0,    4,  102,  103,    0,    0,   96,   97,
   98,   99,  100,  101,  107,    0,    0,    0,    0,    0,
    0,    0,    0,  109,  110,  111,    0,    0,    0,  112,
    0,  105,  106,   47,   48,    0,    0,   78,   80,   81,
   83,    9,    0,    0,    0,    7,    8,    0,   19,    0,
    0,    0,    0,    0,    0,    0,   44,   45,   89,    0,
    0,    0,   73,    0,    0,    0,   25,   26,    0,    0,
    0,    0,    0,    0,    0,    0,   38,   39,   40,   42,
    0,   52,    0,  114,   10,    0,   85,   64,    0,   21,
    6,    0,    0,    0,    0,    0,   87,   63,   71,   72,
    0,    0,   57,   65,   54,   15,   11,   12,    0,    0,
   76,   77,    0,    0,    0,   16,    0,    0,   82,    0,
    0,   17,   14,    0,   18,   13,
};
short yydgoto[] = {                                       2,
    3,  102,   59,   41,   42,   43,   44,   45,   46,   47,
   60,  141,  104,   48,  105,  106,  107,  108,  109,   16,
  122,  123,  124,   49,   50,   51,   52,    8,   63,  145,
   61,  148,  112,  113,  114,   54,  158,  115,  180,   67,
   68,   76,   77,   78,   79,   80,   81,   82,   55,   87,
   88,   89,   91,   56,   94,   95,  146,   57,   58,   97,
  120,   17,   18,   19,   20,   21,   22,   23,
};
short yysindex[] = {                                   -262,
    0,    0,    0, -262, -233,    0,    0, -156,    0,    0,
    0,    0,    0,    0,    0, -236,    0,    0,    0,    0,
    0, -209, -156,    0,    0,  -77,    0,    0,  -77, -196,
    0,    0,    0,    0,    0,    0,    0,    0,    0, -236,
 -177,    0,  -85, -206,    0, -220,    0, -175, -234,    0,
    0,    0,  -83,  -77, -222, -222,    0,    0, -212, -183,
  -77, -262,  -77,    0,    0,    0,  -77,  -77,    0,    0,
    0,    0,    0,    0,    0,  -77,  -77,  -77,  -77,  -77,
  -77,  -77,  -77,    0,    0,    0,  -77,  -77,  -77,    0,
  -77,    0,    0,    0,    0,  -77,  -77,    0,    0,    0,
    0,    0, -240, -176,  -83,    0,    0, -176,    0, -245,
  -83,  -77,  -77, -196, -196, -241,    0,    0,    0, -156,
 -167, -165,    0, -182, -233, -177,    0,    0, -147, -147,
 -147, -147, -147, -147, -206, -206,    0,    0,    0,    0,
 -165,    0, -257,    0,    0,  -77,    0,    0, -236,    0,
    0, -176, -171, -171,  -77,  -77,    0,    0,    0,    0,
 -262, -156,    0,    0,    0,    0,    0,    0, -171, -241,
    0,    0,  -77,  -83, -171,    0, -134,  -77,    0,  -83,
 -165,    0,    0,  -83,    0,    0,
};
short yyrindex[] = {                                      0,
    0,    0,    0,  129,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0, -127,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
 -247,    0,  162,   72,    0,   42,    0,   -9,  -39,    0,
    0,    0, -115,    0,    0,    0,    0,    0, -228,    0,
    0, -109,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0, -100,    0,    0,    0,    0,
    0,    0,  -91,    0,  -75,    0,    0,    0,    0,   12,
 -115, -117,  -99,    0,    0,    0,    0,    0,    0,    0,
 -251,    0,    0,  -79,    0, -202,    0,    0,  167,  197,
  202,  232,  237,  267,  102,  132,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0, -117,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0, -117,    0,    0,    0, -129,  -69,    0,    0,
    0,    0,    0,    0,    0,    0,
};
short yygindex[] = {                                      0,
  194,   14,  -24,  136,   84,   67,   81,   32,    0,  128,
 -108,   90,  -86,    0,   31, -168, -148,   96,  103,  -20,
    0,   48,    0,    1,    0,    0,    0,   86,  196,  -16,
  -19, -102,    0,    0,    0,   -7, -113,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,  -35,    0,
    0,    0,    0,    0,    0,    0,  104,    0,    0,  204,
   87,    0,    0,    0,    0,    0,    0,    0,
};
#define YYTABLESIZE 562
short yytable[] = {                                      27,
    5,   40,   30,  153,    5,  151,   53,   83,  160,  142,
  119,  182,   55,    4,   55,  185,   24,    4,   24,   32,
   24,   28,   62,   64,  157,  177,  142,  163,  103,  116,
   32,  183,   28,  111,   24,  186,  121,   50,    1,   50,
   31,   96,   32,   55,   24,   24,  169,   24,    7,  166,
   24,   24,  144,  110,   25,   24,  174,   28,   25,  165,
    7,   23,  125,   23,  175,   23,   50,  184,   32,  181,
   90,  121,  143,   35,   36,   37,   38,   39,    1,   24,
  149,   84,   85,   86,  119,  111,  103,  147,  121,   23,
   23,  111,   23,   83,   83,   83,   83,   83,   83,  159,
  157,    9,   96,   65,   66,  110,  155,  156,   92,   93,
  144,  110,   10,   11,   12,   13,   14,   15,  137,  138,
  139,  121,  140,   25,   24,  144,  179,    8,    3,    8,
    8,  170,    8,    8,    8,    8,  167,  168,   75,   34,
   51,  172,  129,  130,  131,  132,  133,  134,   20,  149,
  127,  128,  173,    8,  111,  149,   74,    8,  178,  149,
  111,  125,  135,  136,  111,   53,    8,    8,    8,    8,
    8,    8,   55,   98,  110,   99,  100,   51,  101,   31,
  110,   32,  117,  118,  110,   31,   75,   32,   22,   69,
   70,   71,   72,   73,   74,   53,   51,    6,  126,   33,
   75,   34,  154,   34,  176,   33,  152,  150,  171,   34,
  162,   26,   35,   36,   37,   38,   39,    1,   35,   36,
   37,   38,   39,    1,   56,   29,   56,  161,   56,  164,
    0,    0,    0,    0,    0,   56,   56,   56,   56,   56,
   56,   56,   56,    0,   56,   56,   56,   56,   56,   56,
   56,   56,   56,   56,   49,   56,   49,    0,   49,    0,
    0,    0,    0,    0,    0,   49,   49,   49,   49,   49,
   49,   49,   49,    0,    0,   56,   49,   49,   49,   49,
   49,   49,   49,   49,    0,   49,   56,   56,   56,   56,
   56,   56,   56,   56,    0,   56,   56,   56,   56,   56,
   56,   56,   56,   56,   56,   43,   56,   43,    0,   43,
    0,    0,    0,    0,    0,    0,   43,   43,   43,   43,
   43,   43,   43,   43,    0,    0,    0,   43,   43,   43,
   43,   43,    0,   43,   43,   37,   43,   37,    0,   37,
    0,    0,    0,    0,    0,    0,   37,   37,   37,   37,
   37,   37,   37,   37,    0,    0,    0,   37,   37,    0,
    0,    0,    0,   37,   37,   35,   37,   35,    0,   35,
    0,    0,    0,    0,    0,    0,   35,   35,   35,   35,
   35,   35,   35,   35,    0,    0,    0,   35,   35,    0,
    0,    0,    0,   35,   35,   36,   35,   36,    0,   36,
    0,    0,    0,    0,    0,    0,   36,   36,   36,   36,
   36,   36,   36,   36,    0,    0,    0,   36,   36,    0,
    0,    0,    0,   36,   36,   34,   36,   34,    0,   34,
   28,    0,   28,    0,   28,    0,    0,    0,    0,    0,
    0,    0,   34,   34,    0,    0,    0,   28,   28,    0,
    0,    0,    0,   34,   34,    0,   34,    0,   28,   28,
   29,   28,   29,    0,   29,   30,    0,   30,    0,   30,
    0,    0,    0,    0,    0,    0,    0,   29,   29,    0,
    0,    0,   30,   30,    0,    0,    0,    0,   29,   29,
    0,   29,    0,   30,   30,   31,   30,   31,    0,   31,
   32,    0,   32,    0,   32,    0,    0,    0,    0,    0,
    0,    0,   31,   31,    0,    0,    0,   32,   32,    0,
    0,    0,    0,   31,   31,    0,   31,    0,   32,   32,
   33,   32,   33,    0,   33,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,   33,   33,    0,
    0,    0,    0,    0,    0,    0,    0,    0,   33,   33,
    0,   33,
};
short yycheck[] = {                                      16,
    0,   26,   23,  112,    4,  108,   26,   43,  122,   96,
  268,  180,  264,    0,  266,  184,  264,    4,  266,  265,
  268,  267,   30,   40,  266,  174,  113,  141,   53,   54,
  265,  180,  267,   53,  292,  184,   61,  266,  301,  268,
  263,   49,  265,  295,  292,  293,  155,  295,  294,  152,
  292,  292,  293,   53,  295,  292,  170,  267,  295,  146,
  294,  264,   62,  266,  173,  268,  295,  181,  265,  178,
  291,   96,   97,  296,  297,  298,  299,  300,  301,  292,
  105,  288,  289,  290,  268,  105,  111,  264,  113,  292,
  293,  111,  295,  129,  130,  131,  132,  133,  134,  120,
  266,  258,  110,  281,  282,  105,  114,  115,  284,  285,
  293,  111,  269,  270,  271,  272,  273,  274,   87,   88,
   89,  146,   91,  295,  292,  293,  261,  257,    0,  259,
  260,  156,  262,  263,  264,  265,  153,  154,  286,  287,
  268,  162,   76,   77,   78,   79,   80,   81,  264,  174,
   67,   68,  169,  283,  174,  180,  266,  287,  175,  184,
  180,  161,   82,   83,  184,  266,  296,  297,  298,  299,
  300,  301,  264,  257,  174,  259,  260,  295,  262,  263,
  180,  265,   55,   56,  184,  263,  266,  265,  264,  275,
  276,  277,  278,  279,  280,  295,  266,    4,   63,  283,
  286,  287,  113,  287,  174,  283,  111,  105,  161,  287,
  125,   16,  296,  297,  298,  299,  300,  301,  296,  297,
  298,  299,  300,  301,  264,   22,  266,  124,  268,  143,
   -1,   -1,   -1,   -1,   -1,  275,  276,  277,  278,  279,
  280,  281,  282,   -1,  284,  285,  286,  287,  288,  289,
  290,  291,  292,  293,  264,  295,  266,   -1,  268,   -1,
   -1,   -1,   -1,   -1,   -1,  275,  276,  277,  278,  279,
  280,  281,  282,   -1,   -1,  264,  286,  287,  288,  289,
  290,  291,  292,  293,   -1,  295,  275,  276,  277,  278,
  279,  280,  281,  282,   -1,  284,  285,  286,  287,  288,
  289,  290,  291,  292,  293,  264,  295,  266,   -1,  268,
   -1,   -1,   -1,   -1,   -1,   -1,  275,  276,  277,  278,
  279,  280,  281,  282,   -1,   -1,   -1,  286,  287,  288,
  289,  290,   -1,  292,  293,  264,  295,  266,   -1,  268,
   -1,   -1,   -1,   -1,   -1,   -1,  275,  276,  277,  278,
  279,  280,  281,  282,   -1,   -1,   -1,  286,  287,   -1,
   -1,   -1,   -1,  292,  293,  264,  295,  266,   -1,  268,
   -1,   -1,   -1,   -1,   -1,   -1,  275,  276,  277,  278,
  279,  280,  281,  282,   -1,   -1,   -1,  286,  287,   -1,
   -1,   -1,   -1,  292,  293,  264,  295,  266,   -1,  268,
   -1,   -1,   -1,   -1,   -1,   -1,  275,  276,  277,  278,
  279,  280,  281,  282,   -1,   -1,   -1,  286,  287,   -1,
   -1,   -1,   -1,  292,  293,  264,  295,  266,   -1,  268,
  264,   -1,  266,   -1,  268,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,  281,  282,   -1,   -1,   -1,  281,  282,   -1,
   -1,   -1,   -1,  292,  293,   -1,  295,   -1,  292,  293,
  264,  295,  266,   -1,  268,  264,   -1,  266,   -1,  268,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,  281,  282,   -1,
   -1,   -1,  281,  282,   -1,   -1,   -1,   -1,  292,  293,
   -1,  295,   -1,  292,  293,  264,  295,  266,   -1,  268,
  264,   -1,  266,   -1,  268,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,  281,  282,   -1,   -1,   -1,  281,  282,   -1,
   -1,   -1,   -1,  292,  293,   -1,  295,   -1,  292,  293,
  264,  295,  266,   -1,  268,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,  281,  282,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,  292,  293,
   -1,  295,
};
#define YYFINAL 2
#ifndef YYDEBUG
#define YYDEBUG 0
#endif
#define YYMAXTOKEN 301
#if YYDEBUG
char *yyname[] = {
"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"TOKEN_PRINT","TOKEN_FUNCTION",
"TOKEN_FOR","TOKEN_IF","TOKEN_ELSE","TOKEN_RETURN","TOKEN_LEFT_BRACE",
"TOKEN_RIGHT_BRACE","TOKEN_LEFT_PAREN","TOKEN_RIGHT_PAREN","TOKEN_LEFT_BRACKET",
"TOKEN_RIGHT_BRACKET","TOKEN_STRING","TOKEN_INTEGER","TOKEN_CHAR","TOKEN_VOID",
"TOKEN_BOOLEAN","TOKEN_ARRAY","TOKEN_GE","TOKEN_LE","TOKEN_EQ","TOKEN_NE",
"TOKEN_LT","TOKEN_GT","TOKEN_AND","TOKEN_OR","TOKEN_NOT","TOKEN_INCREMENT",
"TOKEN_DECREMENT","TOKEN_ADD","TOKEN_SUBTRACT","TOKEN_MULTIPLY","TOKEN_DIVIDE",
"TOKEN_MODULUS","TOKEN_EXPONENTIATE","TOKEN_ASSIGN","TOKEN_COMMA","TOKEN_COLON",
"TOKEN_SEMICOLON","TOKEN_TRUE","TOKEN_FALSE","TOKEN_CHAR_LITERAL",
"TOKEN_INTEGER_LITERAL","TOKEN_STRING_LITERAL","TOKEN_IDENTIFIER",
};
char *yyrule[] = {
"$accept : program",
"program : decl_list",
"decl_list : decl decl_list",
"decl_list : decl",
"decl : identifier colon type assign expr semicolon",
"decl : identifier colon type semicolon",
"decl : identifier colon type assign left_brace stmt_list right_brace",
"stmt : open_stmt",
"stmt : closed_stmt",
"closed_stmt : decl",
"closed_stmt : expr semicolon",
"closed_stmt : return opt_expr semicolon",
"closed_stmt : print expr_list semicolon",
"closed_stmt : for left_paren opt_expr semicolon opt_expr semicolon opt_expr right_paren closed_stmt",
"closed_stmt : if left_paren expr right_paren closed_stmt else closed_stmt",
"closed_stmt : left_brace stmt_list right_brace",
"open_stmt : if left_paren expr right_paren stmt",
"open_stmt : if left_paren expr right_paren closed_stmt else open_stmt",
"open_stmt : for left_paren opt_expr semicolon opt_expr semicolon opt_expr right_paren open_stmt",
"stmt_list : not_empty_stmt_list",
"stmt_list :",
"not_empty_stmt_list : stmt not_empty_stmt_list",
"not_empty_stmt_list : stmt",
"expr : expr assign and_expr",
"expr : and_expr",
"and_expr : and_expr and compare_expr",
"and_expr : and_expr or compare_expr",
"and_expr : compare_expr",
"compare_expr : add_expr ne add_expr",
"compare_expr : add_expr gt add_expr",
"compare_expr : add_expr ge add_expr",
"compare_expr : add_expr lt add_expr",
"compare_expr : add_expr le add_expr",
"compare_expr : add_expr eq add_expr",
"compare_expr : add_expr",
"add_expr : add_expr add mul_expr",
"add_expr : add_expr subtract mul_expr",
"add_expr : mul_expr",
"mul_expr : mul_expr multiply expon_expr",
"mul_expr : mul_expr divide expon_expr",
"mul_expr : mul_expr modulus expon_expr",
"mul_expr : expon_expr",
"expon_expr : neg_expr exponentiate expon_expr",
"expon_expr : neg_expr",
"neg_expr : subtract incr_expr",
"neg_expr : not incr_expr",
"neg_expr : incr_expr",
"incr_expr : primary_expr increment",
"incr_expr : primary_expr decrement",
"incr_expr : primary_expr",
"opt_expr : expr",
"opt_expr :",
"expr_list : not_empty_expr_list",
"expr_list :",
"not_empty_expr_list : expr comma not_empty_expr_list",
"not_empty_expr_list : expr",
"primary_expr : identifier",
"primary_expr : identifier left_paren expr_list right_paren",
"primary_expr : integer_literal",
"primary_expr : string_literal",
"primary_expr : char_literal",
"primary_expr : true",
"primary_expr : false",
"primary_expr : left_paren expr right_paren",
"primary_expr : left_brace not_empty_expr_list right_brace",
"primary_expr : identifier left_bracket expr right_bracket",
"type : integer",
"type : void",
"type : string",
"type : char",
"type : boolean",
"type : array left_bracket opt_expr right_bracket type",
"type : function type left_paren param_list right_paren",
"param_list : not_empty_param_list",
"param_list :",
"not_empty_param_list : param",
"not_empty_param_list : param comma not_empty_param_list",
"param : identifier colon type",
"print : TOKEN_PRINT",
"function : TOKEN_FUNCTION",
"for : TOKEN_FOR",
"if : TOKEN_IF",
"else : TOKEN_ELSE",
"return : TOKEN_RETURN",
"left_brace : TOKEN_LEFT_BRACE",
"right_brace : TOKEN_RIGHT_BRACE",
"left_paren : TOKEN_LEFT_PAREN",
"right_paren : TOKEN_RIGHT_PAREN",
"left_bracket : TOKEN_LEFT_BRACKET",
"right_bracket : TOKEN_RIGHT_BRACKET",
"string : TOKEN_STRING",
"integer : TOKEN_INTEGER",
"char : TOKEN_CHAR",
"void : TOKEN_VOID",
"boolean : TOKEN_BOOLEAN",
"array : TOKEN_ARRAY",
"ge : TOKEN_GE",
"le : TOKEN_LE",
"eq : TOKEN_EQ",
"ne : TOKEN_NE",
"lt : TOKEN_LT",
"gt : TOKEN_GT",
"and : TOKEN_AND",
"or : TOKEN_OR",
"not : TOKEN_NOT",
"increment : TOKEN_INCREMENT",
"decrement : TOKEN_DECREMENT",
"add : TOKEN_ADD",
"subtract : TOKEN_SUBTRACT",
"multiply : TOKEN_MULTIPLY",
"divide : TOKEN_DIVIDE",
"modulus : TOKEN_MODULUS",
"exponentiate : TOKEN_EXPONENTIATE",
"assign : TOKEN_ASSIGN",
"comma : TOKEN_COMMA",
"colon : TOKEN_COLON",
"semicolon : TOKEN_SEMICOLON",
"true : TOKEN_TRUE",
"false : TOKEN_FALSE",
"char_literal : TOKEN_CHAR_LITERAL",
"integer_literal : TOKEN_INTEGER_LITERAL",
"string_literal : TOKEN_STRING_LITERAL",
"identifier : TOKEN_IDENTIFIER",
};
#endif
#if YYDEBUG
#include <stdio.h>
#endif

/* define the initial stack-sizes */
#ifdef YYSTACKSIZE
#undef YYMAXDEPTH
#define YYMAXDEPTH  YYSTACKSIZE
#else
#ifdef YYMAXDEPTH
#define YYSTACKSIZE YYMAXDEPTH
#else
#define YYSTACKSIZE 10000
#define YYMAXDEPTH  10000
#endif
#endif

#define YYINITSTACKSIZE 500

int      yydebug;
int      yynerrs;
int      yyerrflag;
int      yychar;
short   *yyssp;
YYSTYPE *yyvsp;
YYSTYPE  yyval;
YYSTYPE  yylval;

/* variables for the parser stack */
static short   *yyss;
static short   *yysslim;
static YYSTYPE *yyvs;
static int      yystacksize;
#line 450 "parser.y"

int yyerror(char *str) {
	printf("yytext: %s\n",yytext);
	printf("parse error: %s\n",str);
	return 1;
}
#line 523 "parser.tab.c"
/* allocate initial stack or double stack size, up to YYMAXDEPTH */
static int yygrowstack(void)
{
    int newsize, i;
    short *newss;
    YYSTYPE *newvs;

    if ((newsize = yystacksize) == 0)
        newsize = YYINITSTACKSIZE;
    else if (newsize >= YYMAXDEPTH)
        return -1;
    else if ((newsize *= 2) > YYMAXDEPTH)
        newsize = YYMAXDEPTH;

    i = yyssp - yyss;
    newss = (yyss != 0)
          ? (short *)realloc(yyss, newsize * sizeof(*newss))
          : (short *)malloc(newsize * sizeof(*newss));
    if (newss == 0)
        return -1;

    yyss  = newss;
    yyssp = newss + i;
    newvs = (yyvs != 0)
          ? (YYSTYPE *)realloc(yyvs, newsize * sizeof(*newvs))
          : (YYSTYPE *)malloc(newsize * sizeof(*newvs));
    if (newvs == 0)
        return -1;

    yyvs = newvs;
    yyvsp = newvs + i;
    yystacksize = newsize;
    yysslim = yyss + newsize - 1;
    return 0;
}

#define YYABORT goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR goto yyerrlab
int
yyparse(void)
{
    register int yym, yyn, yystate;
#if YYDEBUG
    register const char *yys;

    if ((yys = getenv("YYDEBUG")) != 0)
    {
        yyn = *yys;
        if (yyn >= '0' && yyn <= '9')
            yydebug = yyn - '0';
    }
#endif

    yynerrs = 0;
    yyerrflag = 0;
    yychar = YYEMPTY;

    if (yyss == NULL && yygrowstack()) goto yyoverflow;
    yyssp = yyss;
    yyvsp = yyvs;
    *yyssp = yystate = 0;

yyloop:
    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;
    if (yychar < 0)
    {
        if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, reading %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
    }
    if ((yyn = yysindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: state %d, shifting to state %d\n",
                    YYPREFIX, yystate, yytable[yyn]);
#endif
        if (yyssp >= yysslim && yygrowstack())
        {
            goto yyoverflow;
        }
        *++yyssp = yystate = yytable[yyn];
        *++yyvsp = yylval;
        yychar = YYEMPTY;
        if (yyerrflag > 0)  --yyerrflag;
        goto yyloop;
    }
    if ((yyn = yyrindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
        yyn = yytable[yyn];
        goto yyreduce;
    }
    if (yyerrflag) goto yyinrecovery;

    yyerror("syntax error");

#ifdef lint
    goto yyerrlab;
#endif

yyerrlab:
    ++yynerrs;

yyinrecovery:
    if (yyerrflag < 3)
    {
        yyerrflag = 3;
        for (;;)
        {
            if ((yyn = yysindex[*yyssp]) && (yyn += YYERRCODE) >= 0 &&
                    yyn <= YYTABLESIZE && yycheck[yyn] == YYERRCODE)
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: state %d, error recovery shifting\
 to state %d\n", YYPREFIX, *yyssp, yytable[yyn]);
#endif
                if (yyssp >= yysslim && yygrowstack())
                {
                    goto yyoverflow;
                }
                *++yyssp = yystate = yytable[yyn];
                *++yyvsp = yylval;
                goto yyloop;
            }
            else
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: error recovery discarding state %d\n",
                            YYPREFIX, *yyssp);
#endif
                if (yyssp <= yyss) goto yyabort;
                --yyssp;
                --yyvsp;
            }
        }
    }
    else
    {
        if (yychar == 0) goto yyabort;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
        yychar = YYEMPTY;
        goto yyloop;
    }

yyreduce:
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: state %d, reducing by rule %d (%s)\n",
                YYPREFIX, yystate, yyn, yyrule[yyn]);
#endif
    yym = yylen[yyn];
    if (yym)
        yyval = yyvsp[1-yym];
    else
        memset(&yyval, 0, sizeof yyval);
    switch (yyn)
    {
case 1:
#line 92 "parser.y"
{
	yyval.decl = yyvsp[0].decl;
	parser_result = yyvsp[0].decl;
	return 0;
}
break;
case 2:
#line 99 "parser.y"
{
	yyvsp[-1].decl -> next = yyvsp[0].decl;
	yyval.decl = yyvsp[-1].decl;
}
break;
case 3:
#line 103 "parser.y"
{
	yyval.decl = yyvsp[0].decl;
}
break;
case 4:
#line 108 "parser.y"
{
	yyval.decl = decl_create(yyvsp[-5].name,yyvsp[-3].type,yyvsp[-1].expr,0,0);
}
break;
case 5:
#line 111 "parser.y"
{
	yyval.decl = decl_create(yyvsp[-3].name,yyvsp[-1].type,0,0,0);
}
break;
case 6:
#line 114 "parser.y"
{
	yyval.decl = decl_create(yyvsp[-6].name,yyvsp[-4].type,0,yyvsp[-1].stmt,0);
}
break;
case 7:
#line 119 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 8:
#line 122 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 9:
#line 127 "parser.y"
{
	yyval.stmt = stmt_create(STMT_DECL,yyvsp[0].decl,0,0,0,0,0);
}
break;
case 10:
#line 130 "parser.y"
{
	yyval.stmt = stmt_create(STMT_EXPR,0,0,yyvsp[-1].expr,0,0,0);
}
break;
case 11:
#line 133 "parser.y"
{
	yyval.stmt = stmt_create(STMT_RETURN,0,0,yyvsp[-1].expr,0,0,0);
}
break;
case 12:
#line 136 "parser.y"
{
	yyval.stmt = stmt_create(STMT_PRINT,0,0,yyvsp[-1].expr,0,0,0);
}
break;
case 13:
#line 139 "parser.y"
{
	yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);
}
break;
case 14:
#line 142 "parser.y"
{
	yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);
}
break;
case 15:
#line 145 "parser.y"
{
	yyval.stmt = stmt_create(STMT_BLOCK,0,0,0,0,yyvsp[-1].stmt,0);
}
break;
case 16:
#line 150 "parser.y"
{
	yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-2].expr,0,yyvsp[0].stmt,0);
}
break;
case 17:
#line 153 "parser.y"
{
	yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);
}
break;
case 18:
#line 156 "parser.y"
{
	yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);
}
break;
case 19:
#line 161 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 20:
#line 164 "parser.y"
{
}
break;
case 21:
#line 168 "parser.y"
{
	yyvsp[-1].stmt -> next = yyvsp[0].stmt;
	yyval.stmt = yyvsp[-1].stmt;
}
break;
case 22:
#line 172 "parser.y"
{
	yyval.stmt = yyvsp[0].stmt;
}
break;
case 23:
#line 177 "parser.y"
{
	yyval.expr = expr_create(EXPR_ASSIGN,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 24:
#line 180 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 25:
#line 184 "parser.y"
{
	yyval.expr = expr_create(EXPR_ADD,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 26:
#line 187 "parser.y"
{
	yyval.expr = expr_create(EXPR_OR,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 27:
#line 190 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 28:
#line 195 "parser.y"
{
	yyval.expr = expr_create(EXPR_NE,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 29:
#line 198 "parser.y"
{
	yyval.expr = expr_create(EXPR_GT,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 30:
#line 201 "parser.y"
{
	yyval.expr = expr_create(EXPR_GE,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 31:
#line 204 "parser.y"
{
	yyval.expr = expr_create(EXPR_LT,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 32:
#line 207 "parser.y"
{
	yyval.expr = expr_create(EXPR_LE,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 33:
#line 210 "parser.y"
{
	yyval.expr = expr_create(EXPR_EQ,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 34:
#line 213 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 35:
#line 218 "parser.y"
{
	yyval.expr = expr_create(EXPR_ADD,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 36:
#line 221 "parser.y"
{
	yyval.expr = expr_create(EXPR_SUB,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 37:
#line 224 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 38:
#line 229 "parser.y"
{
	yyval.expr = expr_create(EXPR_MUL,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 39:
#line 232 "parser.y"
{
	yyval.expr = expr_create(EXPR_DIV,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 40:
#line 235 "parser.y"
{
	yyval.expr = expr_create(EXPR_MOD,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 41:
#line 238 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 42:
#line 243 "parser.y"
{
	yyval.expr = expr_create(EXPR_EXPON,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 43:
#line 246 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 44:
#line 251 "parser.y"
{
	yyval.expr = expr_create(EXPR_NEG,yyvsp[0].expr,0);
}
break;
case 45:
#line 254 "parser.y"
{
	yyval.expr = expr_create(EXPR_NOT,yyvsp[0].expr,0);
}
break;
case 46:
#line 257 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 47:
#line 262 "parser.y"
{
	yyval.expr = expr_create(EXPR_INCR,yyvsp[-1].expr,0);
}
break;
case 48:
#line 265 "parser.y"
{
	yyval.expr = expr_create(EXPR_DECR,yyvsp[-1].expr,0);
}
break;
case 49:
#line 268 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 50:
#line 273 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 51:
#line 276 "parser.y"
{
}
break;
case 52:
#line 280 "parser.y"
{
	yyval.expr = yyvsp[0].expr;
}
break;
case 53:
#line 283 "parser.y"
{
}
break;
case 54:
#line 287 "parser.y"
{
	yyval.expr = expr_create(EXPR_LIST,yyvsp[-2].expr,yyvsp[0].expr);
}
break;
case 55:
#line 290 "parser.y"
{
	yyval.expr = expr_create(EXPR_LIST,yyvsp[0].expr,0);
}
break;
case 56:
#line 295 "parser.y"
{
	yyval.expr = expr_create_name(yyvsp[0].name);
}
break;
case 57:
#line 298 "parser.y"
{
	struct expr *id = expr_create_name(yyvsp[-3].name);
	yyval.expr = expr_create(EXPR_FUNC,id,yyvsp[-1].expr);
}
break;
case 58:
#line 302 "parser.y"
{
	yyval.expr = expr_create_integer_literal(yyvsp[0].integer);
}
break;
case 59:
#line 305 "parser.y"
{
	yyval.expr = expr_create_string_literal(yyvsp[0].name);
}
break;
case 60:
#line 308 "parser.y"
{
	yyval.expr = expr_create_character_literal(yyvsp[0].integer);
}
break;
case 61:
#line 311 "parser.y"
{
	yyval.expr = expr_create_boolean_literal(1);
}
break;
case 62:
#line 314 "parser.y"
{
	yyval.expr = expr_create_boolean_literal(0);
}
break;
case 63:
#line 317 "parser.y"
{
	yyval.expr = yyvsp[-1].expr;
}
break;
case 64:
#line 320 "parser.y"
{
	yyval.expr = yyvsp[-1].expr;
}
break;
case 65:
#line 323 "parser.y"
{
	struct expr *id = expr_create_name(yyvsp[-3].name);
	yyval.expr = expr_create(EXPR_ARRAY_DEREF,id,yyvsp[-1].expr);
}
break;
case 66:
#line 329 "parser.y"
{
	yyval.type = type_create(TYPE_INTEGER,0,0,0);
}
break;
case 67:
#line 332 "parser.y"
{
	yyval.type = type_create(TYPE_VOID,0,0,0);
}
break;
case 68:
#line 335 "parser.y"
{
	yyval.type = type_create(TYPE_STRING,0,0,0);
}
break;
case 69:
#line 338 "parser.y"
{
	yyval.type = type_create(TYPE_CHARACTER,0,0,0);
}
break;
case 70:
#line 341 "parser.y"
{
	yyval.type = type_create(TYPE_BOOLEAN,0,0,0);
}
break;
case 71:
#line 344 "parser.y"
{
	yyval.type = type_create(TYPE_ARRAY,0,yyvsp[0].type,yyvsp[-2].expr);
}
break;
case 72:
#line 347 "parser.y"
{
	yyval.type = type_create(TYPE_FUNCTION,yyvsp[-1].param_list,yyvsp[-3].type,0);
}
break;
case 73:
#line 352 "parser.y"
{
	yyval.param_list = yyvsp[0].param_list;
}
break;
case 74:
#line 355 "parser.y"
{
}
break;
case 75:
#line 359 "parser.y"
{
	yyval.param_list = yyvsp[0].param_list;
}
break;
case 76:
#line 362 "parser.y"
{
	yyvsp[-2].param_list -> next = yyvsp[0].param_list;
	yyval.param_list = yyvsp[-2].param_list;
}
break;
case 77:
#line 368 "parser.y"
{
	yyval.param_list = param_list_create(yyvsp[-2].name,yyvsp[0].type,0);
}
break;
case 119:
#line 415 "parser.y"
{
	char c = yytext[1];
	if (c != '\\')
		yyval.integer = c;
	else {
		char d = yytext[2];
		switch(d) {
			case '0':
				yyval.integer = '\0';
				break;
			case 'n':
				yyval.integer = '\n';
				break;
			default:
				yyval.integer = d;
				break;
		}
	}
}
break;
case 120:
#line 434 "parser.y"
{
	yyval.integer = atoi(yytext);
}
break;
case 121:
#line 437 "parser.y"
{
	char *str = malloc(sizeof(char) * 256);
	strcpy(str,yytext);
	convertString(str);
	yyval.name = str;
}
break;
case 122:
#line 443 "parser.y"
{
	char *id = malloc(sizeof(char) * 256);
	strcpy(id,yytext);
	yyval.name = id;
}
break;
#line 1214 "parser.tab.c"
    }
    yyssp -= yym;
    yystate = *yyssp;
    yyvsp -= yym;
    yym = yylhs[yyn];
    if (yystate == 0 && yym == 0)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", YYPREFIX, YYFINAL);
#endif
        yystate = YYFINAL;
        *++yyssp = YYFINAL;
        *++yyvsp = yyval;
        if (yychar < 0)
        {
            if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
            if (yydebug)
            {
                yys = 0;
                if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
                if (!yys) yys = "illegal-symbol";
                printf("%sdebug: state %d, reading %d (%s)\n",
                        YYPREFIX, YYFINAL, yychar, yys);
            }
#endif
        }
        if (yychar == 0) goto yyaccept;
        goto yyloop;
    }
    if ((yyn = yygindex[yym]) && (yyn += yystate) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yystate)
        yystate = yytable[yyn];
    else
        yystate = yydgoto[yym];
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: after reduction, shifting from state %d \
to state %d\n", YYPREFIX, *yyssp, yystate);
#endif
    if (yyssp >= yysslim && yygrowstack())
    {
        goto yyoverflow;
    }
    *++yyssp = yystate;
    *++yyvsp = yyval;
    goto yyloop;

yyoverflow:
    yyerror("yacc stack overflow");

yyabort:
    return (1);

yyaccept:
    return (0);
}
